config/routes.rb
TaokeSimple::Application.routes.draw do
  get "ad/display",:as=>'ad_display'
  get "ad/show",:as=>'ad_show'
  get "ad/preview",:as=>'ad_preview'
  get "tbshow"=>'ad#show',:as=>'tbshow'
  get "tbdisplay"=>'ad#display',:as=>'tbdisplay'
  get "ad"=>'ad#index',:as=>'ad'

  get "shops/recent",:as=>'recent_shops'
  get "shops/top",:as=>'hot_shops'
  #match "shop/:id" => 'shop#show',:as=>'shop'

  #match '/img/:p1/:p2/:p3' => redirect("http://img%{p1}.taobaocdn.com/bao/uploaded/i%{p2}/%{p3}.jpg")
  match '/img/:p1/:p2(/:p3)/(*all)' => redirect("http://img%{p1}.taobaocdn.com/bao/uploaded/i%{p2}/%{all}.jpg")
  match '/shoplogo/(*all)' => redirect("http://logo.taobaocdn.com/shop-logo/%{all}")
  get "items/recent",:as=>'items_recent'
  get "items/hot",:as=>'items_hot'
  match "item/:id" => 'items#show',:as=>'item'
  match "/status" => 'home#status',:as=>'status'

  match '/outlink/item/:id'=>'items#link',:as=>'item_link'
  match '/outlink/shop/:id'=>'shops#link',:as=>'shop_link'

  resources :words

  devise_for :users
  resources :users
  resque_constraint = lambda do |request|
    Rails.env.development? or 
      (request.env['warden'].authenticate? and request.env['warden'].user.has_role?(:admin))
  end
  constraints resque_constraint do
    mount Resque::Server.new, :at => "/resque"
  end
  constraints :subdomain => 'shop' do
    match ':id' => 'shops#show',:as=>'shop_home'
    root :to => redirect(:subdomain=>Settings.primary_domain)
  end
  if Settings.use_subdomain 
    constraints :subdomain => /[a-z]{4}/ do
      match '/flush'=>'words#flush'
      root :to => 'words#home'
    end
  else
    match ':id' => 'words#home',:as=>'word_home',:constraints=>{:id=>/[a-z]{4,5}/}
  end
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
end

app/controllers/ad_controller.rb
class AdController < ApplicationController
  def index
    @q = params[:q]
  end
  def show
    @id = params[:id] || "preview"
    @q = params[:q]
    @ic = params[:ic]
    if @ic.present?
      @q.encode!('utf-8',@ic)
    end
    respond_to do |format|
      format.js
    end
  end

  def display
    @q = params[:q]
    @ic = params[:ic]
    if @ic.present?
      @q.encode!('utf-8',@ic)
    end
    @items = Taobao::TaokeItemList.search(@q,:page_size=>10,:outer_code=>'63qu').fields('title,pic_url,click_url,promotion_price,nick').order_by('commissionVolume_desc')
    render :layout=>'js'
  end
  def preview
  end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/views/ad/_menu.html.haml
%p
  =link_to "overview",ad_url
  =link_to "preview",ad_preview_url

app/views/ad/display.html.haml
=javascript_tag 'var _hmt = _hmt || [];'
.mk_items
  -i=-1
  -@items.each do |item|
    -i+=1
    -break if i > 10
    .item{:class=>i==1 ? "first" : nil}
      %a{:href=>item.click_url,:rel=>'nofollow',:target=>'_blank',:title=>item.title,:onclick=>"_hmt.push(['_trackEvent','#{item.nick}','#{request.referer}'])"}
        .photo
          =image_tag "#{item.pic_url}_90x90.jpg",:width=>90,:height=>88
        .price  
          =item.promotion_price.to_s.sub(/\.0$/,'')

  <script type="text/javascript">
  var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
  document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F0e1f155833b397eb86d81e6c6aac715b' type='text/javascript'%3E%3C/script%3E"));
  </script>

app/views/ad/index.html.haml
-#= render :partial => 'menu'
%h1 Ad


%h3 预览

%form
  %label{:for=>'q'} 关键词
  %input{:name=>'q',:id=>'q',:value=>@q}
  %input{:type=>'submit','value'=>'预览'} 
-if @q.present?    
  -@code = ad_show_url(:format=>'js',:q=>@q,:id=>'preview')
  %h4 广告代码
  %code=@code
  %h4 广告效果
  #preview


-content_for :footer do
  %script{:src=>@code,:type=>'text/javascript'}

app/views/ad/preview.haml
= render :partial => 'menu'

app/views/ad/show.js.erb
var  MuzikTb = function(q,id,ic){
    document.getElementById(id).innerHTML = '<iframe src="http://www.63qu.com/tbdisplay?q='+q+'&ic='+ic+'" frameborder=0 width=980 height=90 scrolling=no></iframe>';
  }
MuzikTb('<%=@q%>','<%=@id%>','<%=@ic%>');