config/routes.rb
TaokeSimple::Application.routes.draw do
  get "ad/display",:as=>'ad_display'
  get "ad/show",:as=>'ad_show'
  get "ad/preview",:as=>'ad_preview'
  get "tbshow"=>'ad#show',:as=>'tbshow'
  get "tbdisplay"=>'ad#display',:as=>'tbdisplay'
  get "ad"=>'ad#index',:as=>'ad'

  get "shops/recent",:as=>'recent_shops'
  get "shops/top",:as=>'hot_shops'
  #match "shop/:id" => 'shop#show',:as=>'shop'

  #match '/img/:p1/:p2/:p3' => redirect("http://img%{p1}.taobaocdn.com/bao/uploaded/i%{p2}/%{p3}.jpg")
  match '/img/:p1/:p2(/:p3)/(*all)' => redirect("http://img%{p1}.taobaocdn.com/bao/uploaded/i%{p2}/%{all}.jpg")
  match '/shoplogo/(*all)' => redirect("http://logo.taobaocdn.com/shop-logo/%{all}")
  get "items/recent",:as=>'items_recent'
  get "items/hot",:as=>'items_hot'
  match "item/:id" => 'items#show',:as=>'item'
  match "/status" => 'home#status',:as=>'status'

  match '/outlink/item/:id'=>'items#link',:as=>'item_link'
  match '/outlink/shop/:id'=>'shops#link',:as=>'shop_link'

  resources :words

  devise_for :users
  resources :users
  resque_constraint = lambda do |request|
    Rails.env.development? or 
      (request.env['warden'].authenticate? and request.env['warden'].user.has_role?(:admin))
  end
  constraints resque_constraint do
    mount Resque::Server.new, :at => "/resque"
  end
  constraints :subdomain => 'shop' do
    match ':id' => 'shops#show',:as=>'shop_home'
    root :to => redirect(:subdomain=>Settings.primary_domain)
  end
  if Settings.use_subdomain 
    constraints :subdomain => /[a-z]{4}/ do
      match '/flush'=>'words#flush'
      root :to => 'words#home'
    end
  else
    match ':id' => 'words#home',:as=>'word_home',:constraints=>{:id=>/[a-z]{4,5}/}
  end
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #caches_page :index
  def index
  end
  def status
    @data = {
      :items => Item.count,
      :shops => Shop.count,
      :words => Word.count
    }
    render :json=>@data
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_item_list.html.haml
-per_line = 5
-if items.present?
  -limit = items.size
  -lines = limit / per_line
  .carousel.slide.home-slide{:id=>id}
    %h2=title
    .more=link_to "更多",url,:rel=>'nofollow'
    .carousel-inner
      -Range.new(0,lines-1).each do |line|
        .item{:class=>(line.zero? ? 'active' : nil)}
          %ul.item-list
            -i=-1
            -items[line*per_line,per_line].each do |item|
              -i+=1
              %li.tbi{:class=>cycle('a','b','c'),:id=>"item-#{i}"}
                .photo
                  %a{:id=>"external-#{i}",:href=>item_link_url(item),:rel=>'nofollow',:target=>'_blank'}
                    =image_tag  "#{local_path(item.pic_url)}_160x160.jpg",:width=>160,:height=>160
                .hd
                  .title
                    =link_to item.title,item_url(item),:rel=>"nofollow",:target=>'_blank',:id=>"link-#{i}"
                .ft
                  -if item.promotion_price != item.price
                    %del
                      =number_to_currency item.price,:unit=>'¥'
                  %span.price
                    =number_to_currency item.promotion_price,:unit=>'¥'
                %a.pull-right.btn.btn-mini{:href=>item_link_url(item),:rel=>'nofollow',:target=>'_blank'} 去看看
                .volume
                  近日售出#{item.volume}件

    .carousel-control.left{:href=>'#'+id,'data-slide'=>'prev'} &lsaquo;
    .carousel-control.right{:href=>'#'+id,'data-slide'=>'next'} &rsaquo;

  -content_for :end do
    =javascript_include_tag '/assets/jquery.lazyload.js'
    =javascript_tag "$('img.lazy').lazyload({threshold: 200})"
  
-else
  #items_not_found

app/views/home/_recent.html.haml
-limit = 15
-items = Item.recent.limit(limit)
= render :partial => 'item_list',:locals=>{:items=>items,:title=>'最新发现',:url=>items_recent_url,:id=>'recent'}

app/views/home/index.html.haml
%section#recent
  = render :partial => 'recent'
%section#recent
  = render :partial => 'item_list',:locals=>{:items=>Item.hot.limit(15),:title=>'热点推荐',:url=>items_hot_url,:id=>'hot'}
.row
  .widget.span4
    %h4 最近加入
    %ul.words
      -Shop.limit(30).each do |r|
        %li=link_to r.nick,shop_url(r)
  .widget.span4
    -words = Word.published.recent.limit(30)
    %h3 访客正在搜
    -#.more=link_to '更多','/',:rel=>'nofollow'
    %ul.words
      -words.each do |w|
        %li=link_to w.clean_name,w.to_url
  .widget.span4
    %h4 随机推荐
    %ul.words
      -Word.random(30).each do |r|
        %li=link_to r.name,r.to_url