config/routes.rb
TaokeSimple::Application.routes.draw do
  get "ad/display",:as=>'ad_display'
  get "ad/show",:as=>'ad_show'
  get "ad/preview",:as=>'ad_preview'
  get "tbshow"=>'ad#show',:as=>'tbshow'
  get "tbdisplay"=>'ad#display',:as=>'tbdisplay'
  get "ad"=>'ad#index',:as=>'ad'

  get "shops/recent",:as=>'recent_shops'
  get "shops/top",:as=>'hot_shops'
  #match "shop/:id" => 'shop#show',:as=>'shop'

  #match '/img/:p1/:p2/:p3' => redirect("http://img%{p1}.taobaocdn.com/bao/uploaded/i%{p2}/%{p3}.jpg")
  match '/img/:p1/:p2(/:p3)/(*all)' => redirect("http://img%{p1}.taobaocdn.com/bao/uploaded/i%{p2}/%{all}.jpg")
  match '/shoplogo/(*all)' => redirect("http://logo.taobaocdn.com/shop-logo/%{all}")
  get "items/recent",:as=>'items_recent'
  get "items/hot",:as=>'items_hot'
  match "item/:id" => 'items#show',:as=>'item'
  match "/status" => 'home#status',:as=>'status'

  match '/outlink/item/:id'=>'items#link',:as=>'item_link'
  match '/outlink/shop/:id'=>'shops#link',:as=>'shop_link'

  resources :words

  devise_for :users
  resources :users
  resque_constraint = lambda do |request|
    Rails.env.development? or 
      (request.env['warden'].authenticate? and request.env['warden'].user.has_role?(:admin))
  end
  constraints resque_constraint do
    mount Resque::Server.new, :at => "/resque"
  end
  constraints :subdomain => 'shop' do
    match ':id' => 'shops#show',:as=>'shop_home'
    root :to => redirect(:subdomain=>Settings.primary_domain)
  end
  if Settings.use_subdomain 
    constraints :subdomain => /[a-z]{4}/ do
      match '/flush'=>'words#flush'
      root :to => 'words#home'
    end
  else
    match ':id' => 'words#home',:as=>'word_home',:constraints=>{:id=>/[a-z]{4,5}/}
  end
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :isbrand, :keywords, :name, :publish, :slug
  #resourcify
  has_one :itemdata
  before_create :slug_gen
  after_create :init_data

  scope :recent,order('id desc')
  scope :published,where(:publish=>true)
  #scope :random,order('rand()')
  #scope :random,where('id >= (SELECT FLOOR( MAX(id) * RAND()) FROM `words` )')
  scope :short,select('name,slug')
  scope :random,lambda{|limit|
    #more = (limit * 1.5).ceil
    #lid = select(:id).last.id - limit
    #offset = rand(1..lid)
    #where('id > ?',offset).limit(limit)
    ids = search_for_ids :per_page=>limit,:sort_by=>'@random'
    where(:id=>ids)
  }
  
  @queue = "p2"
  def self.perform id,method,*args
    find(id).send(method, *args)
  end
  def async(method, *args)
    Resque.enqueue(Word, id, method, *args)
  end
  define_index do
    indexes :name
    has :id
    has :isbrand,:facets=>true
    where sanitize_sql(["publish", true])
    set_property :delta => ThinkingSphinx::Deltas::ResqueDelta
  end
  DOMAIN = ENV["DOMAIN"]
  def to_url
    @url ||= Settings.use_subdomain ? "http://#{slug}#{DOMAIN}" : "http://www#{DOMAIN}/#{slug}"
  end
  def clean_name
    @clean_name ||= name.gsub(/ /,'')
  end

  def init_data
    #Resque.enqueue UpdateKeywords,id
    #Resque.enqueue UpdateItems,id
    async(:with_delay,:update_keywords) if Settings.baidu_related_words?
    async(:with_delay,:update_items)
  end
  def check_published
    update_attribute :publish,true if items.present?
  end
  def publish!
    update_attribute :publish,true
  end
  def slug_gen
    base = self[:slug].present? ? self[:slug] : random_slug
    while self.class.select(:id).where(:slug=>base).first.present?
      base = random_slug
    end
    self[:slug] = base
  end
  def slug_regen
    update_attribute :slug,slug_gen
  end
  def title
    @title ||= begin
                 if keywords.present?  
                   arr = keywords.split(',')
                   ([clean_name] + arr[0,2]).join('_')
                 else
                   clean_name
                 end
               end
  end
  def keywords_hash
    @keywords_hash ||= (keywords.present? ? keywords.split(',') : [])
  end
  def random_slug
    #rand(479890..1679615).to_s 36
    ('a'..'z').to_a.sample(5).join('')
  end
  def update_keywords
    update_attribute :keywords,RelatedWords::Baidu.query(name).join(',')
  end
  def with_delay method
    keep_time 1 do
      send method rescue nil
    end
  end
  def update_keywords_with_delay
    keep_time 1 do
      update_keywords rescue nil
    end
  end
  def items
    itemdata.present? ? YAML.load(itemdata.data) : nil
  end
  def update_itemdata
    url = 'http://s.m.taobao.com/search_turn_page_iphone.htm'
    response = Typhoeus::Request.get url,:params=>{:q=>name,:topSearch=>1,:from=>1,:sst=>1}
    if response.success?
      data = JSON.parse(response.body)
      Itemdata.where(:word_id=>id).first_or_create :data=>data["listItem"]
      check_published
    end
  end
  def update_items
    Taobao::TaokeItemList.search(name).each do |item|
      Item.import_taoke_item(item)
    end
    publish!
  end
  def related limit=10
    ids = Word.search_for_ids name,
            :without=>{:id=>id},
            :match_mode => :any,
            :per_page => limit
    ids.present? ? Word.short.where(:id=>ids) : []
  end
  def preload
    Typhoeus::Request.get "#{to_url}/flush"
    Typhoeus::Request.get to_url
  end

  class << self
    def import
      where('id > 8733').find_each do |r|
          keep_time 1 do
            r.update_items
          end
      end
    end
    def preload
      select('id').find_each do |r|
        r.async :preload
      end
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  caches_page :home
  # GET /words
  # GET /words.json
  def index
    authorize! :manage,Word
    @words = Word.page(params[:page] || 1).per(100)
    @words = @words.where(:isbrand=>true) if params.has_key? :isbrand
    @words = @words.where(:publish=>eval(params[:publish])) if params.has_key? :publish

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end
  def home
    @slug = params.has_key?(:id) ? params[:id] : request.subdomain
    @word = Word.find_by_slug @slug
    #@rands = Word.short.random.limit(10)
    @items = Item.search @word.name,
                        :match_mode => :any,
                        :include => :shop,
                        :per_page => 40

    @rands = Word.random(30).short
    @relates = @word.related 10
  end
  def flush
    @word = Word.find_by_slug request.subdomain
    expire_page :action=>:home
    redirect_to :action=>:home
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def fake_img url
    "/static/#{url.match(/\/([^\/]+?)_90x90.jpg/)[1]}"
  end
end

app/views/words/_form.html.haml
= simple_form_for(@word) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :slug
    = f.input :publish
    = f.input :isbrand
    = f.input :keywords

  .form-actions
    = f.button :submit

app/views/words/edit.html.haml
%h1 Editing word

= render 'form'

= link_to 'Show', @word
\|
= link_to 'Back', words_path

app/views/words/home.haml
-#-@hide_nav =true
-title @word.title,nil,false
-meta :keywords,@word.keywords_hash[0,3].join(',')
%h1#name=@word.clean_name
=javascript_tag "replaceLink();"
%p=sprintf('<strong>%1$s网</strong>精选<strong>%1$s</strong>信息,产品排行,店铺推荐,买家评价.',@word.clean_name).html_safe

%h2 #{@word.clean_name}产品推荐
= render :partial => 'items/list',:locals=>{:items=>@items}

.row-fluid
  .widget.span4
    %h3 店铺推荐
    -if @items
      %ul.shops.words
        -@items.collect{|r| r.shop}.uniq.slice(0,20).each do |shop|
          %li{:class=>cycle('a','b')}
            =link_to shop.nick,shop_url(shop)
  -if @relates.present?
    .widget.span2
      %h4 相关搜索
      %ul
        -@relates.each do |r|
          %li=link_to r.clean_name,r.to_url
  -if @rands
    .widget.span6
      %h4 随机推荐
      %ul.words
        -@rands.each do |r|
          %li=link_to r.clean_name,r.to_url

.alert.alert-notice#word-notice
  %strong 提示
  以上为淘宝网#{@word.clean_name}买家评价、产品排行、店家排行，由#{@word.clean_name}导购网整理，若要查看更多淘宝网#{@word.clean_name}相关数据，请点击页面顶部链接进入#{@word.clean_name}天猫淘宝商城查看。

-content_for :footer do
  =link_to @word.clean_name,@word.to_url
  =@meta[:keywords]


-content_for :head do
  ="<script id=\"apjs\" type=\"text/javascript\" src=\"http://assets#{ENV["DOMAIN"]}/static/app.js\" data=\"#{CGI.escape @word.name}\"></script>".html_safe

app/views/words/index.html.haml
%h1 Listing words
=link_to 'all',words_url
=link_to 'brand',words_url(:isbrand=>true)
=link_to 'published',words_url(:publish=>true)
=link_to 'unpublished',words_url(:publish=>false)

=paginate @words
%table.table
  %tr
    %th Name
    %th Slug
    %th Publish
    %th Isbrand
    %th Keywords
    %th
    %th
    %th

  - @words.each do |word|
    %tr
      %td=link_to word.name,root_url(:subdomain=>word.slug)
      %td= word.slug
      %td= word.publish
      %td= word.isbrand
      %td= word.keywords
      %td= link_to 'Show', word
      %td= link_to 'Edit', edit_word_path(word)
      %td= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Word', new_word_path

app/views/words/new.html.haml
%h1 New word

= render 'form'

= link_to 'Back', words_path

app/views/words/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @word.name
%p
  %b Slug:
  = @word.slug
%p
  %b Publish:
  = @word.publish
%p
  %b Isbrand:
  = @word.isbrand
%p
  %b Keywords:
  = @word.keywords

= link_to 'Edit', edit_word_path(@word)
\|
= link_to 'Back', words_path